/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package internalPages;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author kinselwyn
 */
public class dashBoardPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashBoardPage
     */
    public dashBoardPage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuDashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sortpane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        queuepane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        linkedlistpane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stackpane = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        arraypane = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        searchpane = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        menuDashboard.setBackground(new java.awt.Color(255, 241, 225));
        menuDashboard.setPreferredSize(new java.awt.Dimension(650, 410));
        menuDashboard.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Menu Driven Program");
        menuDashboard.add(jLabel1);
        jLabel1.setBounds(10, 10, 270, 31);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Data Structures");
        menuDashboard.add(jLabel4);
        jLabel4.setBounds(10, 40, 180, 20);

        sortpane.setBackground(new java.awt.Color(210, 96, 26));
        sortpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sortpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sortpaneMouseExited(evt);
            }
        });
        sortpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sort");
        sortpane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/sortings.png"))); // NOI18N
        sortpane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 110));

        menuDashboard.add(sortpane);
        sortpane.setBounds(440, 240, 130, 120);

        queuepane.setBackground(new java.awt.Color(210, 96, 26));
        queuepane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                queuepaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                queuepaneMouseExited(evt);
            }
        });
        queuepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/queue.png"))); // NOI18N
        queuepane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Queue");
        queuepane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 30));

        menuDashboard.add(queuepane);
        queuepane.setBounds(60, 240, 130, 120);

        linkedlistpane.setBackground(new java.awt.Color(210, 96, 26));
        linkedlistpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkedlistpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkedlistpaneMouseExited(evt);
            }
        });
        linkedlistpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/linked.png"))); // NOI18N
        linkedlistpane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Linked List");
        linkedlistpane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 20));

        menuDashboard.add(linkedlistpane);
        linkedlistpane.setBounds(250, 80, 130, 120);

        stackpane.setBackground(new java.awt.Color(210, 96, 26));
        stackpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stackpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stackpaneMouseExited(evt);
            }
        });
        stackpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/stacked.png"))); // NOI18N
        stackpane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Stack");
        stackpane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 20));

        menuDashboard.add(stackpane);
        stackpane.setBounds(440, 80, 130, 120);

        arraypane.setBackground(new java.awt.Color(210, 96, 26));
        arraypane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arraypaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arraypaneMouseExited(evt);
            }
        });
        arraypane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Array");
        arraypane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 30));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/array.png"))); // NOI18N
        arraypane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 90));

        menuDashboard.add(arraypane);
        arraypane.setBounds(60, 80, 130, 120);

        searchpane.setBackground(new java.awt.Color(210, 96, 26));
        searchpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchpaneMouseExited(evt);
            }
        });
        searchpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Search");
        searchpane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 30));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/search.png"))); // NOI18N
        searchpane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        menuDashboard.add(searchpane);
        searchpane.setBounds(260, 240, 130, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    Color navcolor = new Color(29, 60, 69);
    Color headcolor = new Color(210, 96, 26);
    Color bodycolor = new Color(255, 241, 225);
    
    private void arraypaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arraypaneMouseEntered
        arraypane.setBackground(navcolor);
    }//GEN-LAST:event_arraypaneMouseEntered

    private void arraypaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arraypaneMouseExited
        arraypane.setBackground(headcolor);
    }//GEN-LAST:event_arraypaneMouseExited

    private void linkedlistpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedlistpaneMouseEntered
        linkedlistpane.setBackground(navcolor);
    }//GEN-LAST:event_linkedlistpaneMouseEntered

    private void linkedlistpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedlistpaneMouseExited
        linkedlistpane.setBackground(headcolor);
    }//GEN-LAST:event_linkedlistpaneMouseExited

    private void stackpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stackpaneMouseEntered
        stackpane.setBackground(navcolor);
    }//GEN-LAST:event_stackpaneMouseEntered

    private void stackpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stackpaneMouseExited
        stackpane.setBackground(headcolor);
    }//GEN-LAST:event_stackpaneMouseExited

    private void queuepaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queuepaneMouseEntered
        queuepane.setBackground(navcolor);
    }//GEN-LAST:event_queuepaneMouseEntered

    private void queuepaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queuepaneMouseExited
        queuepane.setBackground(headcolor);
    }//GEN-LAST:event_queuepaneMouseExited

    private void searchpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchpaneMouseEntered
        searchpane.setBackground(navcolor);
    }//GEN-LAST:event_searchpaneMouseEntered

    private void searchpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchpaneMouseExited
        searchpane.setBackground(headcolor);
    }//GEN-LAST:event_searchpaneMouseExited

    private void sortpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortpaneMouseEntered
        sortpane.setBackground(navcolor);
    }//GEN-LAST:event_sortpaneMouseEntered

    private void sortpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortpaneMouseExited
        sortpane.setBackground(headcolor);
    }//GEN-LAST:event_sortpaneMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arraypane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel linkedlistpane;
    private javax.swing.JPanel menuDashboard;
    private javax.swing.JPanel queuepane;
    private javax.swing.JPanel searchpane;
    private javax.swing.JPanel sortpane;
    private javax.swing.JPanel stackpane;
    // End of variables declaration//GEN-END:variables
}
